language: go
go_import_path: go.universe.tf/metallb
os:
- linux
go:
- 1.8
- 1.9
- tip
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
script:
- glide install
- go install -v go.universe.tf/metallb/controller go.universe.tf/metallb/bgp-speaker
- go test $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
jobs:
  include:
  - stage: deploy
    go: 1.9
    env:
    - NAME=build_containers
    script: true
    deploy:
    - provider: script
      script: go run dockerfiles/trigger_build.go
      on:
        branch: master
env:
  global:
  # QUAY_TRIGGER_URL_CONTROLLER
  - secure: rlohP2gBX5+rlBF/WoUlxltNqvlvEoWuKPd1m4SNa5lDj7pS4Sifc6eO0GUNLg3zs7aaT7mN2jXBUnGez0Wlw9ndfw6Axg5jHxtxwbXTod+YGUjnT/PmWLR1iaAoub7BzkPZenPJWJSzlabCxAX4JyXYPOXiq0GuYpANFxisw8ef1EUQn8kOgkrxlmbQ6xnwe79ctA4ryuu4czoOeo/ciMuGBiFrTfXHzCJzOkxCLDJIQL5duwF+i+qcmAtCmHimU4UCIAzj5cYTfZQamwJWShdd59tcJfT/GTP7zgnnQakihwe55w9sXjJ6R/KDtmoYWgKTQmf/9TqlzVXNAM3SLPpVlRPsCrcRUsY9SfeGWYH58YN+GIWh5cFnCRVY+0v6RzMid2TA4yYbgYwHQQ8Aq/zlfa9nhu6mOKIlcndHGf6FT9Z2S9wU9UowIqR9b0hnGp9vjDnMYKqwzarp7oQ6suIC/uZOq+KThawI0WBQsLX6Sak25uU0VZm4nmZ2boJQuD3CkADQPLwjO44MWXOHBgsAvJdWGyFt//nNp96Cx6yJ80gJr9bP7ovx0GqwH4l/JmlluGEQscsfMW9QYX4nsJzSiwohNLf+EEjkaBBTJL++TjdEPOew8+U5jM1k1SVPp1F67iSHIhe3B2SnKpEwGM0LDyQGyMxG34YqYOUxqX0=
  # QUAY_TRIGGER_URL_BGP_SPEAKER
  - secure: E31ADXzhy1jgxtEiUza94DijnF1MxC8K/QQmNdF4rBc239cxb3UkHXPYhdrUEe+iCuvmkHEXPSjb2pxguQfqVsDIcwZkrKTt9hohWB7H5bZwgKl0wGYxxwkNM8L1xKZQx4dNuhV2Nh/mQummTiVZEMR9ZNBB/TUglmli1K7YgxcoeiWUisQhHMZushyF5lcMRjKJFGybCU/00Sz4CS1q5rm8RsmWeN1d4gNgHo4xcAfRbqNYW8js7OTJFYVuykLC+if4rk+K6KtgDOqJiXPeDqNLZruFTdI8puM9ALne74y+LWkpdlHUfKfv0dz18fRXPYwzUQuMN6r4hLTmaxIXTgWzK3/eg0o4IggI6GgdRMHp9ZTFtYKrs9TbhhCqD79QsCiwRBC0Pn3FRI8ZUEIgud0T+j0zGnCl41Fr/2SzdKa8TRej4bAWB2GKSiJSyZtbOR27nWcbhWTDyFxWzUQp+rq5z/2Oidm1KEI/mMTCUjmYEsMpMKIUwIvzUH2FXEir4TX2NqnP333s5sez9/nyZUhUmoIhkgeTXY+Q0mozU58MvlBaXWhm4gtJBAY5WDwQevWSHVj9fzBPddpTtMx4gRKiV49RDz2maEWr5amfxTnQR5RS4jG4ES6emP+ShEe+nEALhSMNvSl0vmy/FzKZc8ukKeJSBHi33YsQ4qzhVc8=
