language: go
go_import_path: go.universe.tf/metallb
os:
- linux
go:
- 1.8
- 1.9
- tip
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
script:
- glide install
- go install -v go.universe.tf/metallb/controller go.universe.tf/metallb/bgp-speaker
- go test $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
jobs:
  include:
  - stage: deploy
    go: 1.9
    env:
    - NAME=build_containers
    script: true
    deploy:
    - provider: script
      script: go run dockerfiles/trigger_build.go
      on:
        branch: master
env:
  global:
  # QUAY_TRIGGER_URL_CONTROLLER
  - secure: R7dOq5uuryndhdUqnKCixHngIjtZm4X3SX2VDv3wwjKB8mr/a3tKAW9ZYQlcI4YVLr+XuzU9V7gRFDPVe1tdCtmY4HiwAism0enc7wPiGkoD7YLoXXTCw6/3oZ/3L4D/5gwHUDVKFYxetPo7S4+ZWLepTPbSnIEVWULY3hMCiA5E2GIMsXWQxxFeRdyV/x2pmiOgIuj0QuIDDmicuxHJ5CPqwEP1qEBRkvShJTIqtK9tdppfZWoE+o4rYsUv2FvTDecgEBfsikGEJc6FhQyU9PBe+KmwmBRk1n6HnAz7FDky4q9WQs0zZbOrtzdh4IIdWlkrJ94Meqzxl6+ee6zYH1qhJM5WVqFKyq37/ojhrFqDa569+3JcHPAlA0/23/nSK8l42gdlbdT0NqhA/zdVP/oGdwrmlYSwZGYEWVNy87Byj9tN2PsasLWNoVWrEZxhrq3PzB4YtFcSBkrBR034TZMMBqkcuPq4AWv6WP15u1GlVqmyTddQKYf5GjcBoTf9/4cDpEZBnvy0/6sgCsA8MLi0UTQMH4QgDBCSW41mXf6f8u3Ja3e7qdhydcFhe/n+CKoq/KPcoLHt1JSA0TA3v9cvN9jFcYkGH3MkkeBJwpr/g9zbZnoLyoWcseD4PmhLBPMqJzKeMZ2NnfklJLHRIFUJt7H1OdPHuYn3XA2nRDo=
  # QUAY_TRIGGER_URL_BGP_SPEAKER
  - secure: H1SheaGzWQ8dbLnBsoxTqO6HbnafsNuYFRZ9h/DCfy7Wfj9jmnUJmCMpZ8zI3HIPJFYPMY2MaMj5HLteWEM0ttqx1UrknfXAUTHlZL2ROocOH5J2hdDUNXhcgjz3HHwIysBgcExkL1pP4abhzdft1bdioL6pT4fp0CRReBUlnxFwYZMMuzA64FQT25ffi4mWmfWqKda6KCaaX3VVLkmnuo/5bm83cr0I8qSXAsWSwzF7aSGmo6/XYWn1tyXVB8i7XSnmBlLHZk4X+JGhqBOxkebwMI7UH4m9D53LsL/FFniExUqFeLCW2EAtE9k6DG2lTErtlaql21Gtq7WTcFX360BSkG0nHw4PkIHmAR4pgArxzS1MoXdJYrBInR1xw7k1jvPQe6I2gt67whqMteIdJlONdeAYAm5RwlYwQNost9/46Tbo1ZVLbpGs4LKNPjSMmnkQaLOl9J7a14qASCXvDuU2kdiwrUF9yZA6csuCyKcNQZ5FL2jmQ4DrkT+v+xtRT97jhgx0mBmwJMMLQaFHen9FudinOE6Ron5wTnCdsBhS+PogQqNZcAX46MpELciWY8kyBcshjCSXWrvSGgTtRYYS5yFNo7ip73VzxGJJStWpsRuSzdjnxI2pxBryfeVbxomqDu02KNFCiYcnMiAkeO8waAQuU5I2pzcrpP5t2W8=
