apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    peers:
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.0.0.100
    address-pools:
    - name: demo
      cidr:
      - 192.0.2.0/24 # TEST-NET-1
      advertisements:
      - localpref: 100
